version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    image: chat-server
    container_name: chat-backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
  
    volumes:
      - ./server/src:/app/src

volumes: 
  mongodb_data:
